4 TO - DO - Task
Please complete all the problem listed below.
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [8]:
#TASK1
import numpy as np
e_array=np.empty((2,2))
print("Empty array with size 2x2\n",e_array)

Empty array with size 2x2
 [[4.71010555e-310 0.00000000e+000]
 [6.61959372e-310 6.61959372e-310]]


In [9]:
#TASK2
import numpy as np
o_array=np.ones((4,2))
print("All one array with 4x2\n",o_array)

All one array with 4x2
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
#TASK3
import numpy as np
f_array=np.full((3,3),fill_value=7)
print("New array filled with 7\n",f_array)

New array filled with 7
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [10]:
#TASK4
z_array=np.zeros_like(f_array)
print("New array pf zeros with same shape and type as reference array\n",z_array)

New array pf zeros with same shape and type as reference array
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
#Task5
o_array=np.ones_like(f_array)
print("New array of ones with same shape and type as reference array\n",o_array)

New array of ones with same shape and type as reference array
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
#TASK6
n_list=[1,2,3,4]
converted_array=np.array(n_list)
print("Numpy array converted to list\n",converted_array)

Numpy array converted to list
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [25]:
#TASK1
import numpy as np
a1 = np.arange(10,50)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [27]:
#TASK2
a2=np.arange(9).reshape(3,3)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
#TASK3
a3= np.eye(3)
print(a3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
a4=np.random.random(30)
print(a4.mean())

0.49591311088451884


In [32]:
a5= np.random.random((10,10))
print("Minimum value",a5.min())
print("Maximum value",a5.max())



Minimum value 0.010891743142872001
Maximum value 0.989150624479211


In [33]:
a6= np.zeros(10)
a6[4]=1
print(a6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [34]:
a7=np.array([1,2,0,0,4,0])
r_arr=np.flip(a7)
print("reverse array",r_arr)

reverse array [0 4 0 0 2 1]


In [35]:
a8= np.ones((5,5))
a8[1:-1, 1:-1]=0
print(a8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
a9=np.zeros((8,8),int)
a9[1::2, ::2]=1
a9[::2, 1::2]=1
print(a9)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [38]:
import numpy as np
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
z=np.add(x,y)
print("ADDITION OF ARRAY:\n",z)


ADDITION OF ARRAY:
 [[ 6  8]
 [10 13]]


In [39]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
z=np.subtract(x,y)
print("SUBRACTION OF ARRAY:\n",z)


SUBRACTION OF ARRAY:
 [[-4 -4]
 [-4 -3]]


In [40]:
a=np.array([[1,2],[3,5]])
print("MULTIPLICATION OF ARRAY:\n",a*3)

MULTIPLICATION OF ARRAY:
 [[ 3  6]
 [ 9 15]]


In [41]:
a=np.array([[1,2],[3,5]])
b=np.square(a)
print("Square of array",b)

Square of array [[ 1  4]
 [ 9 25]]


In [42]:
v=np.array([9,10])
w=np.array([11,12])
x=np.array([9,10])
y=np.array([11,12])
print("Dot product between v and w: ",np.dot(v,w))
print("Dot product between x and v: ",np.dot(x,v))
print("Dot product between x and y: ",np.dot(x,y))

Dot product between v and w:  219
Dot product between x and v:  181
Dot product between x and y:  219


In [48]:
import numpy as np
a = np.array([[1,2],[3,5]])
b = np.array([[5,6],[7,8]])
v =np.array([9,10])
w=np.array([11,12])
concat_ab=np.concatenate((a,b),axis=0)
concat_vw =np.vstack((v,w)).T
print("Concatenate a and b along rows\n",concat_ab)
print("Concatenate v and w along column\n",concat_vw)

Concatenate a and b along rows
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column
 [[ 9 11]
 [10 12]]


In [47]:
a = np.array([[1,2],[3,5]])
b= np.array([9,10])
result = np.concatenate((a,b),axis=0)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [50]:
import numpy as np
a= np.array([[3,4],[5,6]])
a_inv= np.linalg.inv(a)
result=np.dot(a,a_inv)
print("A * A^(-1)",result)

A * A^(-1) [[ 1.0000000e+00 -8.8817842e-16]
 [ 0.0000000e+00  1.0000000e+00]]


In [51]:
a= np.array([[3,4],[5,6]])
b= np.array([[1,2],[7,8]])
print("AB \n",np.dot(a,b))
print("BA \n",np.dot(b,a))

AB 
 [[31 38]
 [47 58]]
BA 
 [[13 16]
 [61 76]]


In [53]:
a= np.array([[3,4],[5,6]])
b= np.array([[1,2],[7,8]])
ab_trans=np.transpose(np.dot(a,b))
aTbT=np.dot(b.T,a.T)
print("Transpose of AB \n",ab_trans)
print("Transpose of BA \n",aTbT)

Transpose of AB 
 [[31 47]
 [38 58]]
Transpose of BA 
 [[31 47]
 [38 58]]


In [56]:
a= np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
b=np.array([-1,-3,9])
a_inv = np.linalg.inv(a)
result=np.dot(a_inv,b)
print("solution of linear equation",result)

solution of linear equation [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [65]:
#TASK1
import time
import numpy as np
l1=[i for i in range(1000000)]
l2=[i for i in range(1000000)]
start=time.time()
result=[l1[i] + l2[i] for i in range(1000000)]
end=time.time()
print("Time taken for python list addition",(end-start))

a1= np.arange(1000000)
a2=np.arange(1000000)
s = time.time()
result1 = a1 + a2
e=time.time()
print("Time taken for array addition",(e-s))




Time taken for python list addition 0.17451977729797363
Time taken for array addition 0.004498004913330078


In [59]:
#TASK2
import time
import numpy as np
l1=[i for i in range(1000000)]
l2=[i for i in range(1000000)]
start=time.time()
result=[l1[i] * l2[i] for i in range(1000000)]
end=time.time()
print("Time taken for python list multiplication",(end-start))

a1= np.arange(1000000)
a2=np.arange(1000000)
s = time.time()
result1 = a1 * a2
e=time.time()
print("Time taken for array multiplication",(e-s))




Time taken for python list 0.1680605411529541
Time taken for python list 0.04389357566833496


In [61]:
#TASK3
import time
import numpy as np
l1=[i for i in range(1000000)]
l2=[i for i in range(1000000)]
start=time.time()
result=sum(l1[i] * l2[i] for i in range(1000000))
end=time.time()
print("Time taken for python list dot product",(end-start))

a1= np.arange(1000000)
a2=np.arange(1000000)
start_t = time.time()
result1 = np.dot(a1,a2)
end_t=time.time()
print("Time taken for dot product",(end_t-start_t))



Time taken for python list dot product 0.28705334663391113
Time taken for dot product 0.0019290447235107422


In [66]:
#TASK4
import time
import numpy as np
m1=[[i for i in range(1000)]for j in range (100)]
m2=[[i for i in range(1000)]for j in range (100)]
start=time.time()
result=[[sum(m1[i][k] * m2[k][j] for k in range(100))for j in range(100)] for i in range(100)]
end=time.time()
print("Time taken for python list matrix ,multiplication",(end-start))

a1= np.random.rand(100,100)
a2=np.random.rand(100,100)
start_t = time.time()
result1 = np.dot(a1,a2)
end_t=time.time()
print("Time taken for array matrix multiplication",(end_t-start_t))


Time taken for python list matrix ,multiplication 0.23958134651184082
Time taken for array matrix multiplication 0.0004096031188964844
